export { default as Burger } from './Burger';
export { default as Letter} from './Letter';
export { default as Phone } from './Phone';
export { default as Pointer } from './Pointer';
export { default as Tg } from './Tg';
export { default as Wa } from './Wa';
export { default as Cross } from './Cross';
export { default as Figure } from './Figure';
export { default as BackgroundCirclesMagnifier } from './BackgroundCirclesMagnifier';
export { default as BackgroundCirclesEducation } from './BackgroundCirclesEducation';
export { default as BackgroundCirclesSpecialization } from './BackgroundCirclesSpecialization';
export { default as BackgroundCirclesServices } from './BackgroundCirclesServices';
export { default as BackgroundCirclesNav } from './BackgroundCirclesNav';
export { default as BackgroundCirclesBanner } from './BackgroundCirclesBanner';
